#!/usr/bin/env bash
# Entrypoint for the Cyrus host. Starts a local Postgres whose data dir lives on
# the persistent volume, then drops privileges and execs the Cyrus agent in the
# foreground (Fly restarts the machine if it exits).
set -euo pipefail

CYRUS_HOME=/home/cyrus
STATE_DIR="${CYRUS_HOME}/.cyrus"          # Fly volume mount point
export PGDATA="${STATE_DIR}/pgdata"

# The volume mounts root-owned on first boot. Hand the top-level state dir to the
# cyrus user (its config, repos, worktrees, and mise cache live here), but give
# Postgres its own pgdata subdir — initdb runs as the postgres user and can't
# write into a cyrus-owned directory. Chown only these two roots (NOT -R), so an
# already-initialized pgdata keeps its postgres ownership across reboots.
mkdir -p "${STATE_DIR}"
chown cyrus:cyrus "${STATE_DIR}"

# Initialize the cluster once. The bootstrap superuser is `postgres`, and we set
# its password to `postgres` to match what app dev configs expect.
if [ ! -s "${PGDATA}/PG_VERSION" ]; then
  echo "==> Initializing PostgreSQL cluster at ${PGDATA}"
  mkdir -p "${PGDATA}"
  chown postgres:postgres "${PGDATA}"
  chmod 700 "${PGDATA}"
  PWFILE="$(mktemp)"
  echo "postgres" > "${PWFILE}"
  chown postgres:postgres "${PWFILE}"
  gosu postgres /usr/lib/postgresql/*/bin/initdb \
    --username=postgres --auth-local=trust --auth-host=scram-sha-256 \
    --pwfile="${PWFILE}" -D "${PGDATA}"
  rm -f "${PWFILE}"
  echo "listen_addresses = 'localhost'" >> "${PGDATA}/postgresql.conf"
fi

echo "==> Starting PostgreSQL"
gosu postgres /usr/lib/postgresql/*/bin/pg_ctl -D "${PGDATA}" \
  -o "-c listen_addresses=localhost -p 5432" -w start

# Set the git committer identity to the GitHub App's "[bot]" account so commits
# and PRs share one identity. Derived live from the App (no hardcoded IDs);
# best-effort — if the GH_APP_* secrets are missing or the API is unreachable, we
# leave the baked fallback (see Dockerfile) rather than fail the boot.
echo "==> Resolving git committer identity from the GitHub App"
if identity="$(gosu cyrus env HOME="${CYRUS_HOME}" gh-app-token git-identity 2>/dev/null)" \
   && [ -n "${identity}" ]; then
  eval "${identity}"
  gosu cyrus env HOME="${CYRUS_HOME}" git config --global user.name  "${CYRUS_GIT_NAME}"
  gosu cyrus env HOME="${CYRUS_HOME}" git config --global user.email "${CYRUS_GIT_EMAIL}"
  echo "    committer: ${CYRUS_GIT_NAME} <${CYRUS_GIT_EMAIL}>"
else
  echo "    WARN: could not derive App identity; using baked fallback"
fi

echo "==> Starting Cyrus agent as cyrus user"
cd "${CYRUS_HOME}"
# Put mise's shim dir on PATH so the agent's non-interactive shells resolve
# per-repo runtimes (mix, elixir, node, …) directly. The `mise activate` line in
# .bashrc only works in interactive shells AND only updates PATH via a per-prompt
# hook — neither holds for the one-shot `bash -c` commands the agent runs, so a
# bare `mix` would otherwise fail with "command not found". Shims are static
# executables that pick the right version from the worktree's .tool-versions at
# exec time, so they work in any shell. They live under MISE_DATA_DIR (on the
# volume) and are generated by `mise install` during cyrus-setup.sh.
MISE_SHIMS="${MISE_DATA_DIR:-${CYRUS_HOME}/.local/share/mise}/shims"
# Prepend the shims INSIDE the login shell, after it has sourced /etc/profile.
# `bash -l` re-runs /etc/profile, which hard-resets PATH
# (PATH="/usr/local/bin:/usr/bin:/bin:…") — so prepending via `env PATH=…` out
# here would be silently clobbered before `exec cyrus`, leaving the agent without
# the shims and a bare `mix` failing. Setting it after the profile runs makes it
# stick, and every `bash -c` the agent spawns inherits it.
# Pin HOME so git (and anything $HOME-based) resolves to /home/cyrus, where the
# baked .gitconfig and the volume-backed .cyrus state both live.
exec gosu cyrus env HOME="${CYRUS_HOME}" MISE_SHIMS="${MISE_SHIMS}" \
  bash -lc 'export PATH="${MISE_SHIMS}:$PATH"; exec cyrus'
